config/routes.rb
Rails.application.routes.draw do
  
  get '/hoowon2' => 'hoowon2#index'

  resources :hoowons
  get '/hoowons' => 'hoowon#index'
  get 'home/index'
  root 'vote_logs#index'

  #vote_logs routing
  resources :vote_logs
  resources :pledgenewees
  get 'home/index'
  post 'vote_logs/checkDouble' => 'vote_logs#checkDouble'

  #pledges routing
  get '/pledges' => 'pledges#index'
  

  #수영 routing
  get '/participate' => 'participate#index'
  get '/random' => 'lottos#new' 

  get 'home/quiz'     # 임시페이지
  get 'home/quizcard' # 임시페이지(블라인드공략테스트)
  resources :routers
  resources :voters
  resources :lottos
  devise_for :admins
  devise_for :users
  resources :pledgeintros

  get '/faq' => 'home#faq'
  get '/routers' => 'routers#index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin' # merge할 때 제일 마지막줄에 위치하게 해주세요!!
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hoowon.rb
class Hoowon < ApplicationRecord
end

app/models/lotto.rb
class Lotto < ApplicationRecord
    serialize :lotarray    
end

app/models/pledgeintro.rb
class Pledgeintro < ActiveRecord::Base
    mount_uploader :image, S3Uploader
end

app/models/pledgenewee.rb
class Pledgenewee < ActiveRecord::Base
    mount_uploader :image, S3Uploader
    mount_uploader :image2, S3Uploader
end

app/models/router.rb
class Router < ApplicationRecord
end

app/models/school_db.rb
class SchoolDb < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
    mount_uploader :image, S3Uploader

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def faq
  end

  def quizcard

  end
end

app/controllers/lottos_controller.rb
class LottosController < ApplicationController
  before_action :set_lotto, only: [:show, :edit, :update, :destroy]
 

  # GET /lottos.json
  def index
    @lotto = Lotto.last
    
  end

  # GET /lottos/1
  # GET /lottos/1.json
  def show
    $total = VoteLog.all.count
   ## 임시코드 xxx
    #for k in 0..@lotto.winnum.to_i
    #  instance_variable_set "@winner_#{k}" , Voter.where(id: $result[k]).pluck(:studentid).to_s.gsub('{"studentid"=>','').gsub('}','')
    #end   

   ##테스트 코드 xxx
    #@firstwinner = Voter.where(id: $result[0]).pluck(:studentid).to_s.gsub('{"studentid"=>','').gsub('}','')
  end

  # GET /lottos/new
  def new
    @lotto = Lotto.new
  end

  # GET /lottos/1/edit
  def edit
  end

  # POST /lottos
  # POST /lottos.json
  def create
    @lotto = Lotto.new(lotto_params)
    
    
    $winnerarray = []
    @totalNum = VoteLog.last.id
    @cnt = 0


    if @lotto.winnum.to_i > VoteLog.count
      $winnerarray.append("ERROR! 응모자 수 < 당첨자 수")
     
    
    else
      while @cnt<@lotto.winnum.to_i
        @ranNum = rand(0..@totalNum)
        @dangchumID = VoteLog.where(id: @ranNum).pluck(:studentid)
        
        #랜덤으로 뽑힌 id가 실제로도 존재하는 지 확인, 뽑힌 id가 다시 뽑히지 않았나 확인
        if VoteLog.exists?(id:@ranNum) &&  !($winnerarray.include? @dangchumID)
          $winnerarray.append(@dangchumID)
          @cnt = @cnt+1  
        end
      end
      
    end    
    

    


    respond_to do |format|
      if @lotto.save
        format.html { redirect_to @lotto, notice: 'Lotto was successfully created.' }
        format.json { render :show, status: :created, location: @lotto }
      else
        format.html { render :new }
        format.json { render json: @lotto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lottos/1
  # PATCH/PUT /lottos/1.json
  def update
    respond_to do |format|
      if @lotto.update(lotto_params)
        format.html { redirect_to @lotto, notice: 'Lotto was successfully updated.' }
        format.json { render :show, status: :ok, location: @lotto }
      else
        format.html { render :edit }
        format.json { render json: @lotto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lottos/1
  # DELETE /lottos/1.json
  def destroy
    @lotto.destroy
    respond_to do |format|
      format.html { redirect_to lottos_url, notice: 'Lotto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lotto
      @lotto = Lotto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lotto_params
      params.require(:lotto).permit(:totalnum, :winnum, :result, :firstwinner, :resultnum)
    end
end

app/controllers/pledgeintros_controller.rb
class PledgeintrosController < ApplicationController
  before_action :set_pledgeintro, only: [:show, :edit, :update, :destroy]

  # GET /pledgeintros
  # GET /pledgeintros.json
  def index
    @pledgeintros = Pledgeintro.all
  end

  # GET /pledgeintros/1
  # GET /pledgeintros/1.json
  def show
  end

  # GET /pledgeintros/new
  def new
    @pledgeintro = Pledgeintro.new
  end

  # GET /pledgeintros/1/edit
  def edit
  end

  # POST /pledgeintros
  # POST /pledgeintros.json
  def create
    @pledgeintro = Pledgeintro.new(pledgeintro_params)

    respond_to do |format|
      if @pledgeintro.save
        format.html { redirect_to @pledgeintro, notice: 'Pledgeintro was successfully created.' }
        format.json { render :show, status: :created, location: @pledgeintro }
      else
        format.html { render :new }
        format.json { render json: @pledgeintro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pledgeintros/1
  # PATCH/PUT /pledgeintros/1.json
  def update
    respond_to do |format|
      if @pledgeintro.update(pledgeintro_params)
        format.html { redirect_to @pledgeintro, notice: 'Pledgeintro was successfully updated.' }
        format.json { render :show, status: :ok, location: @pledgeintro }
      else
        format.html { render :edit }
        format.json { render json: @pledgeintro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pledgeintros/1
  # DELETE /pledgeintros/1.json
  def destroy
    @pledgeintro.destroy
    respond_to do |format|
      format.html { redirect_to pledgeintros_url, notice: 'Pledgeintro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pledgeintro
      @pledgeintro = Pledgeintro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pledgeintro_params
      params.require(:pledgeintro).permit(:title, :content, :content2, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hoowon2_helper.rb
module Hoowon2Helper
end

app/helpers/hoowons_helper.rb
module HoowonsHelper
end

app/helpers/lottos_helper.rb
module LottosHelper
end

app/helpers/participate_helper.rb
module ParticipateHelper
end

app/helpers/pledgeintros_helper.rb
module PledgeintrosHelper
end

app/helpers/pledgenewees_helper.rb
module PledgeneweesHelper
end

app/helpers/routers_helper.rb
module RoutersHelper
end

app/helpers/vote_logs_helper.rb
module VoteLogsHelper
end

app/views/pledgeintros/_form.html.erb
<%= form_for(pledgeintro) do |f| %>
  <% if pledgeintro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pledgeintro.errors.count, "error") %> prohibited this pledgeintro from being saved:</h2>

      <ul>
      <% pledgeintro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :content2 %>
    <%= f.text_area :content2 %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image,
        accept: 'image/png,image/gif,image/jpeg' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pledgeintros/edit.html.erb
<h1>Editing Pledgeintro</h1>

<%= render 'form', pledgeintro: @pledgeintro %>

<%= link_to 'Show', @pledgeintro %> |
<%= link_to 'Back', pledgeintros_path %>

app/views/pledgeintros/index.html.erb
<head>
  <style>
    .Poster {
      height: auto;
      width: 100%;
    }
  </style>
</head>


<p id="notice"><%= notice %></p>

<div class="container">
  <table>
    <tbody>
      <% @pledgeintros.each do |pledgeintro| %>
        <tr>
          <td><%= link_to image_tag("#{pledgeintro.image}", class: "Poster"), pledges_path %></td>
        </tr>
    </tbody>
  </table>
      <%= link_to '확인', pledgeintro %> |
      <%= link_to '변경', edit_pledgeintro_path(pledgeintro) %> |
      <%= link_to '삭제', pledgeintro, method: :delete, data: { confirm: '삭제하시겠습니까?' } %>
      <% end %>

<br><br>

<%= link_to '선거본부 포스터 등록하기', new_pledgeintro_path %>

</div>

app/views/pledgeintros/new.html.erb
<h1>New Pledgeintro</h1>

<%= render 'form', pledgeintro: @pledgeintro %>

<%= link_to 'Back', pledgeintros_path %>

app/views/pledgeintros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pledgeintro.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @pledgeintro.content %>
</p>

<p>
  <strong>Content2:</strong>
  <%= @pledgeintro.content2 %>
</p>

  <table>
    <td><%= image_tag("#{@pledgeintro.image}", style: "height:30%; width: auto;") %></td>
  </table>

<%= link_to 'Edit', edit_pledgeintro_path(@pledgeintro) %> |
<%= link_to 'Back', pledgeintros_path %>