config/routes.rb
Rails.application.routes.draw do
  
  get '/hoowon2' => 'hoowon2#index'

  resources :hoowons
  get '/hoowons' => 'hoowon#index'
  get 'home/index'
  root 'vote_logs#index'

  #vote_logs routing
  resources :vote_logs
  resources :pledgenewees
  get 'home/index'
  post 'vote_logs/checkDouble' => 'vote_logs#checkDouble'

  #pledges routing
  get '/pledges' => 'pledges#index'
  

  #수영 routing
  get '/participate' => 'participate#index'
  get '/random' => 'lottos#new' 

  get 'home/quiz'     # 임시페이지
  get 'home/quizcard' # 임시페이지(블라인드공략테스트)
  resources :routers
  resources :voters
  resources :lottos
  devise_for :admins
  devise_for :users
  resources :pledgeintros

  get '/faq' => 'home#faq'
  get '/routers' => 'routers#index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin' # merge할 때 제일 마지막줄에 위치하게 해주세요!!
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hoowon.rb
class Hoowon < ApplicationRecord
end

app/models/lotto.rb
class Lotto < ApplicationRecord
    serialize :lotarray    
end

app/models/pledgeintro.rb
class Pledgeintro < ActiveRecord::Base
    mount_uploader :image, S3Uploader
end

app/models/pledgenewee.rb
class Pledgenewee < ActiveRecord::Base
    mount_uploader :image, S3Uploader
    mount_uploader :image2, S3Uploader
end

app/models/router.rb
class Router < ApplicationRecord
end

app/models/school_db.rb
class SchoolDb < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
    mount_uploader :image, S3Uploader

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def faq
  end

  def quizcard

  end
end

app/controllers/lottos_controller.rb
class LottosController < ApplicationController
  before_action :set_lotto, only: [:show, :edit, :update, :destroy]
 

  # GET /lottos.json
  def index
    @lotto = Lotto.last
    
  end

  # GET /lottos/1
  # GET /lottos/1.json
  def show
    $total = VoteLog.all.count
   ## 임시코드 xxx
    #for k in 0..@lotto.winnum.to_i
    #  instance_variable_set "@winner_#{k}" , Voter.where(id: $result[k]).pluck(:studentid).to_s.gsub('{"studentid"=>','').gsub('}','')
    #end   

   ##테스트 코드 xxx
    #@firstwinner = Voter.where(id: $result[0]).pluck(:studentid).to_s.gsub('{"studentid"=>','').gsub('}','')
  end

  # GET /lottos/new
  def new
    @lotto = Lotto.new
  end

  # GET /lottos/1/edit
  def edit
  end

  # POST /lottos
  # POST /lottos.json
  def create
    @lotto = Lotto.new(lotto_params)
    
    
    $winnerarray = []
    @totalNum = VoteLog.last.id
    @cnt = 0


    if @lotto.winnum.to_i > VoteLog.count
      $winnerarray.append("ERROR! 응모자 수 < 당첨자 수")
     
    
    else
      while @cnt<@lotto.winnum.to_i
        @ranNum = rand(0..@totalNum)
        @dangchumID = VoteLog.where(id: @ranNum).pluck(:studentid)
        
        #랜덤으로 뽑힌 id가 실제로도 존재하는 지 확인, 뽑힌 id가 다시 뽑히지 않았나 확인
        if VoteLog.exists?(id:@ranNum) &&  !($winnerarray.include? @dangchumID)
          $winnerarray.append(@dangchumID)
          @cnt = @cnt+1  
        end
      end
      
    end    
    

    


    respond_to do |format|
      if @lotto.save
        format.html { redirect_to @lotto, notice: 'Lotto was successfully created.' }
        format.json { render :show, status: :created, location: @lotto }
      else
        format.html { render :new }
        format.json { render json: @lotto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lottos/1
  # PATCH/PUT /lottos/1.json
  def update
    respond_to do |format|
      if @lotto.update(lotto_params)
        format.html { redirect_to @lotto, notice: 'Lotto was successfully updated.' }
        format.json { render :show, status: :ok, location: @lotto }
      else
        format.html { render :edit }
        format.json { render json: @lotto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lottos/1
  # DELETE /lottos/1.json
  def destroy
    @lotto.destroy
    respond_to do |format|
      format.html { redirect_to lottos_url, notice: 'Lotto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lotto
      @lotto = Lotto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lotto_params
      params.require(:lotto).permit(:totalnum, :winnum, :result, :firstwinner, :resultnum)
    end
end

app/controllers/pledgenewees_controller.rb
class PledgeneweesController < ApplicationController
  before_action :set_pledgenewee, only: [:show, :edit, :update, :destroy]

  # GET /pledgenewees
  # GET /pledgenewees.json
  def index
    @pledgenewees = Pledgenewee.all
  end

  # GET /pledgenewees/1
  # GET /pledgenewees/1.json
  def show
  end

  # GET /pledgenewees/new
  def new
    @pledgenewee = Pledgenewee.new
  end

  # GET /pledgenewees/1/edit
  def edit
  end

  # POST /pledgenewees
  # POST /pledgenewees.json
  def create
    @pledgenewee = Pledgenewee.new(pledgenewee_params)

    respond_to do |format|
      if @pledgenewee.save
        format.html { redirect_to @pledgenewee, notice: 'Pledgenewee was successfully created.' }
        format.json { render :show, status: :created, location: @pledgenewee }
      else
        format.html { render :new }
        format.json { render json: @pledgenewee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pledgenewees/1
  # PATCH/PUT /pledgenewees/1.json
  def update
    respond_to do |format|
      if @pledgenewee.update(pledgenewee_params)
        format.html { redirect_to @pledgenewee, notice: 'Pledgenewee was successfully updated.' }
        format.json { render :show, status: :ok, location: @pledgenewee }
      else
        format.html { render :edit }
        format.json { render json: @pledgenewee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pledgenewees/1
  # DELETE /pledgenewees/1.json
  def destroy
    @pledgenewee.destroy
    respond_to do |format|
      format.html { redirect_to pledgenewees_url, notice: 'Pledgenewee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pledgenewee
      @pledgenewee = Pledgenewee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pledgenewee_params
      params.require(:pledgenewee).permit(:name, :title, :content, :title2, :content2, :title3, :content3, :image, :image2)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hoowon2_helper.rb
module Hoowon2Helper
end

app/helpers/hoowons_helper.rb
module HoowonsHelper
end

app/helpers/lottos_helper.rb
module LottosHelper
end

app/helpers/participate_helper.rb
module ParticipateHelper
end

app/helpers/pledgeintros_helper.rb
module PledgeintrosHelper
end

app/helpers/pledgenewees_helper.rb
module PledgeneweesHelper
end

app/helpers/routers_helper.rb
module RoutersHelper
end

app/helpers/vote_logs_helper.rb
module VoteLogsHelper
end

app/views/pledgenewees/_form.html.erb
<%= form_for(pledgenewee) do |f| %>
  <% if pledgenewee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pledgenewee.errors.count, "error") %> prohibited this pledgenewee from being saved:</h2>

      <ul>
      <% pledgenewee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <p>선거본부 후보팀</p>
      <%= f.label :name, '후보팀 : ' %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <p>첫 번재 공약</p>
      <%= f.label :title, '제목 : ' %>
      <%= f.text_field :title %>
    </div>
  
    <div class="field">
      <%= f.label :content, '세부 설명 : ' %>
      <%= f.text_area :content %>
    </div>

    <div class="field">
      <p>두 번재 공약</p>
      <%= f.label :title2, '제목 : ' %>
      <%= f.text_field :title2 %>
    </div>

    <div class="field">
      <%= f.label :content2, '세부 설명 : '%>
      <%= f.text_area :content2 %>
    </div>

    <div class="field">
      <p>세 번재 공약</p>
      <%= f.label :title3, '제목 : ' %>
      <%= f.text_field :title3 %>
    </div>

    <div class="field">
      <%= f.label :content3, '세부 설명 : '%>
      <%= f.text_area :content3 %>
    </div>

  <div class="field">
    <%= f.label :image, '선거본부 포스터 이미지' %>
    <%= f.file_field :image,
        accept: 'image/png,image/gif,image/jpeg' %>
  </div>

    <div class="field">
    <%= f.label :image2, '선거본부 배너 이미지' %>
    <%= f.file_field :image2,
        accept: 'image/png,image/gif,image/jpeg' %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pledgenewees/edit.html.erb
<h1>Editing Pledgenewee</h1>

<%= render 'form', pledgenewee: @pledgenewee %>

<%= link_to 'Show', @pledgenewee %> |
<%= link_to 'Back', pledgenewees_path %>

app/views/pledgenewees/index.html.erb
  <head>
    <script src="http://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>      
  
  </head>
 
  <body>
  <div class="container">
    <div class="poster_bar"></div>
      <p class= "poster_intro"><strong> 올해의 선거본부 후보단을 소개합니다! </strong></p>
    <p id="notice"><%= notice %></p>
    <div class="d-sm-flex flex-sm-column align-items-center">
            <% @pledgenewees.each do |pledgenewee| %>
              <%= link_to image_tag("#{pledgenewee.image}", class: "poster_image"), pledgenewee %>
                  <%# <%= link_to '확인', pledge | %>
                  <%# <%= link_to '변경', edit_pledge_path(pledge) %>
                  <%# <%= link_to '삭제', pledge, method: :delete, data: { confirm: '삭제하시겠습니까?' } %>
                  <%# <p class="poster_name"><%= pledgenewee.name %></p>
                  <div class="poster_bar2"></div>
            <% end %>
    </div>
    
  <div class="poster_footer fixed-bottom navbar-light d-flex justify-content-center">
    <%= link_to '공약 포스터 및 상세 공약 등록하기', new_pledgenewee_path, class: "poster_font" %>
  </div>
</div>
</body>

app/views/pledgenewees/new.html.erb
<h1>New Pledgenewee</h1>

<%= render 'form', pledgenewee: @pledgenewee %>

<%= link_to 'Back', pledgenewees_path %>

app/views/pledgenewees/show.html.erb
<head>
  <script src="http://code.jquery.com/jquery-1.12.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  <script>
    $(document).ready(function(){
        $("#spreadBtn1").click(function(){
            if($("#hiddenList1").is(":visible")){
              $("#spreadBtn1").toggleClass("fas fa-arrow-alt-circle-right fas fa-arrow-alt-circle-down");
                $("#hiddenList1").slideUp();
            }else{
                $("#spreadBtn1").toggleClass("fas fa-arrow-alt-circle-down fas fa-arrow-alt-circle-right");
                $("#hiddenList1").slideDown();
            }
        });
    }); 
    $(document).ready(function(){
        $("#spreadBtn2").click(function(){
            if($("#hiddenList2").is(":visible")){
              $("#spreadBtn2").toggleClass("fas fa-arrow-alt-circle-right fas fa-arrow-alt-circle-down");
                $("#hiddenList2").slideUp();
            }else{
                $("#spreadBtn2").toggleClass("fas fa-arrow-alt-circle-down fas fa-arrow-alt-circle-right");
                $("#hiddenList2").slideDown();
            }
        });
    }); 
    $(document).ready(function(){
        $("#spreadBtn3").click(function(){
            if($("#hiddenList3").is(":visible")){
              $("#spreadBtn3").toggleClass("fas fa-arrow-alt-circle-right fas fa-arrow-alt-circle-down");
                $("#hiddenList3").slideUp();
            }else{
                $("#spreadBtn3").toggleClass("fas fa-arrow-alt-circle-down fas fa-arrow-alt-circle-right");
                $("#hiddenList3").slideDown();
            }
        });
    }); 
  </script>
<head>

<body>
  <div class="col-9 container">
      <p id="notice"><%= notice %></p>
              <div class="banner_bar0"></div>
              <p class="banner_intro"><strong> "클릭"으로 알아보는 세부 공약! </strong></p>    
              <%= image_tag("#{@pledgenewee.image2}", class: "banner_image")%>
              <br>
              <div class="banner_bar1"></div>
                  <p id="spreadBtn1" class="fas fa-arrow-alt-circle-right btn01"><strong> 첫 번째:  </strong><%= @pledgenewee.title %></p>
              <div id="hiddenList1" class="example01 shadow p-3 mb-5 bg-light rounded">
                  <% @list = @pledgenewee.content.split(",") %>
                  <% i = 0 %>
                  <% for x in @list %>
                      <%= i = i + 1 %> <%= ". #{x}" %> <p> </p>
                  <% end %>
              </div>

              <div class="banner_bar2"></div>
              <p id="spreadBtn2" class="fas fa-arrow-alt-circle-right btn02"><strong> 두 번째:  </strong><%= @pledgenewee.title2 %></p>
              <div id="hiddenList2" class="example02 shadow p-3 mb-5 bg-light rounded">
                  <% @list2 = @pledgenewee.content2.split(",") %>
                  <% i = 0 %>
                  <% for x in @list2 %>
                      <%= i = i + 1 %> <%= ". #{x}" %> <p> </p>
                  <% end %>
              </div>

              <div class="banner_bar3"></div>
              <span id="spreadBtn3" class="fas fa-arrow-alt-circle-right btn03"><strong> 세 번째:  </strong><%= @pledgenewee.title3 %></span>
              <div id="hiddenList3" class="example03 shadow p-3 mb-5 bg-light rounded">
                  <% @list3 = @pledgenewee.content3.split(",") %>
                  <% i = 0 %>
                  <% for x in @list3 %>
                      <%= i = i + 1 %> <%= ". #{x}" %> <p> </p>
                  <% end %>
              </div>

    <%# <div class="banner_footer navbar fixed-bottom navbar-light">
      <%= link_to '수정', edit_pledgenewee_path(@pledgenewee), class:"banner_footer_edit"%>
      <%# <%= link_to '삭제', @pledgenewee, method: :delete, data: { confirm: '관리자님 지우시겠어요?' }, class:"banner_footer_delete" %>
      <%# <%= link_to '뒤로가기', pledgenewees_path, class:"banner_footer_back" %>
    <%# </div> %>
  </div>
</body>