config/routes.rb
Rails.application.routes.draw do
  
  get '/hoowon2' => 'hoowon2#index'

  resources :hoowons
  get '/hoowons' => 'hoowon#index'
  get 'home/index'
  root 'vote_logs#index'

  #vote_logs routing
  resources :vote_logs
  resources :pledgenewees
  get 'home/index'
  post 'vote_logs/checkDouble' => 'vote_logs#checkDouble'

  #pledges routing
  get '/pledges' => 'pledges#index'
  

  #수영 routing
  get '/participate' => 'participate#index'
  get '/random' => 'lottos#new' 

  get 'home/quiz'     # 임시페이지
  get 'home/quizcard' # 임시페이지(블라인드공략테스트)
  resources :routers
  resources :voters
  resources :lottos
  devise_for :admins
  devise_for :users
  resources :pledgeintros

  get '/faq' => 'home#faq'
  get '/routers' => 'routers#index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin' # merge할 때 제일 마지막줄에 위치하게 해주세요!!
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hoowon.rb
class Hoowon < ApplicationRecord
end

app/models/lotto.rb
class Lotto < ApplicationRecord
    serialize :lotarray    
end

app/models/pledgeintro.rb
class Pledgeintro < ActiveRecord::Base
    mount_uploader :image, S3Uploader
end

app/models/pledgenewee.rb
class Pledgenewee < ActiveRecord::Base
    mount_uploader :image, S3Uploader
    mount_uploader :image2, S3Uploader
end

app/models/router.rb
class Router < ApplicationRecord
end

app/models/school_db.rb
class SchoolDb < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
    mount_uploader :image, S3Uploader

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def faq
  end

  def quizcard

  end
end

app/controllers/lottos_controller.rb
class LottosController < ApplicationController
  before_action :set_lotto, only: [:show, :edit, :update, :destroy]
 

  # GET /lottos.json
  def index
    @lotto = Lotto.last
    
  end

  # GET /lottos/1
  # GET /lottos/1.json
  def show
    $total = VoteLog.all.count
   ## 임시코드 xxx
    #for k in 0..@lotto.winnum.to_i
    #  instance_variable_set "@winner_#{k}" , Voter.where(id: $result[k]).pluck(:studentid).to_s.gsub('{"studentid"=>','').gsub('}','')
    #end   

   ##테스트 코드 xxx
    #@firstwinner = Voter.where(id: $result[0]).pluck(:studentid).to_s.gsub('{"studentid"=>','').gsub('}','')
  end

  # GET /lottos/new
  def new
    @lotto = Lotto.new
  end

  # GET /lottos/1/edit
  def edit
  end

  # POST /lottos
  # POST /lottos.json
  def create
    @lotto = Lotto.new(lotto_params)
    
    
    $winnerarray = []
    @totalNum = VoteLog.last.id
    @cnt = 0


    if @lotto.winnum.to_i > VoteLog.count
      $winnerarray.append("ERROR! 응모자 수 < 당첨자 수")
     
    
    else
      while @cnt<@lotto.winnum.to_i
        @ranNum = rand(0..@totalNum)
        @dangchumID = VoteLog.where(id: @ranNum).pluck(:studentid)
        
        #랜덤으로 뽑힌 id가 실제로도 존재하는 지 확인, 뽑힌 id가 다시 뽑히지 않았나 확인
        if VoteLog.exists?(id:@ranNum) &&  !($winnerarray.include? @dangchumID)
          $winnerarray.append(@dangchumID)
          @cnt = @cnt+1  
        end
      end
      
    end    
    

    


    respond_to do |format|
      if @lotto.save
        format.html { redirect_to @lotto, notice: 'Lotto was successfully created.' }
        format.json { render :show, status: :created, location: @lotto }
      else
        format.html { render :new }
        format.json { render json: @lotto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lottos/1
  # PATCH/PUT /lottos/1.json
  def update
    respond_to do |format|
      if @lotto.update(lotto_params)
        format.html { redirect_to @lotto, notice: 'Lotto was successfully updated.' }
        format.json { render :show, status: :ok, location: @lotto }
      else
        format.html { render :edit }
        format.json { render json: @lotto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lottos/1
  # DELETE /lottos/1.json
  def destroy
    @lotto.destroy
    respond_to do |format|
      format.html { redirect_to lottos_url, notice: 'Lotto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lotto
      @lotto = Lotto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lotto_params
      params.require(:lotto).permit(:totalnum, :winnum, :result, :firstwinner, :resultnum)
    end
end

app/controllers/routers_controller.rb
class RoutersController < ApplicationController
  before_action :set_router, only: [:show, :edit, :update, :destroy]

  # GET /routers
  # GET /routers.json

  def load_routers  
    @routers_default = Gmaps4rails.build_markers(Router.all) do |plot, marker|  
      marker.lat plot.latitude  
      marker.lng plot.longitude  

      # url_alert = "redicon.png"

      # marker.picture({  
      #   "url" => url_alert,  
      #   "width" => 25,  
      #   "height" => 25  
      # })  

      marker.infowindow render_to_string(:partial => "/routers/info",   
        :locals => {:name => plot.name, :placename => plot.placename })  
    end  
  end

  def index
    load_routers 
    @routers = Router.all
  end

  # GET /routers/1
  # GET /routers/1.json
  def show
  end

  # GET /routers/new
  def new
    @router = Router.new
  end

  # GET /routers/1/edit
  def edit
  end

  # POST /routers
  # POST /routers.json
  def create
    @router = Router.new(router_params)

    respond_to do |format|
      if @router.save
        format.html { redirect_to @router, notice: 'Router was successfully created.' }
        format.json { render :show, status: :created, location: @router }
      else
        format.html { render :new }
        format.json { render json: @router.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routers/1
  # PATCH/PUT /routers/1.json
  def update
    respond_to do |format|
      if @router.update(router_params)
        format.html { redirect_to @router, notice: 'Router was successfully updated.' }
        format.json { render :show, status: :ok, location: @router }
      else
        format.html { render :edit }
        format.json { render json: @router.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routers/1
  # DELETE /routers/1.json
  def destroy
    @router.destroy
    respond_to do |format|
      format.html { redirect_to routers_url, notice: 'Router was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_router
      @router = Router.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def router_params
      params.require(:router).permit(:name, :placename, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hoowon2_helper.rb
module Hoowon2Helper
end

app/helpers/hoowons_helper.rb
module HoowonsHelper
end

app/helpers/lottos_helper.rb
module LottosHelper
end

app/helpers/participate_helper.rb
module ParticipateHelper
end

app/helpers/pledgeintros_helper.rb
module PledgeintrosHelper
end

app/helpers/pledgenewees_helper.rb
module PledgeneweesHelper
end

app/helpers/routers_helper.rb
module RoutersHelper
end

app/helpers/vote_logs_helper.rb
module VoteLogsHelper
end

app/views/routers/_form.html.erb
<%= form_for(router) do |f| %>
  <% if router.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(router.errors.count, "error") %> prohibited this router from being saved:</h2>

      <ul>
      <% router.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :placename %>
    <%= f.text_field :placename %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routers/_info.html.erb
<b>건물명 :</b> <%= name %><br>  
<b>투표 장소 :</b> <%= placename %><br>

app/views/routers/edit.html.erb
<h1>Editing Router</h1>

<%= render 'form', router: @router %>

<%= link_to 'Show', @router %> |
<%= link_to 'Back', routers_path %>

app/views/routers/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
    <div class="howto_bar">
    </div>
    <div class="howto_text_title">
        고려대학교 제51대 총학생회장단 
        <br> 선거 투표기간
    </div>

    <div class="howto_text_box d-flex align-items-start flex-column">
           <p class="howto_text_title2">12월 5일(화) ~ 12월 7일(목)</p>
           <p class="howto_text_title2">투표구는 오전 9시 30분부터 오후 6시 30분까지 운영됩니다.</p>
    </div>

<%# <h1>고려대학교 총학생회장단 선거 투표기간</h1>
<p>12월 5일(화) ~ 12월 7일(목)</p>
<p>투표구는 오전 9시 30분부터 오후 6시 30분까지 운영됩니다.</p>

<h1>고려대학교 총학생회장단 선거 투표장소</h1> %>

    <div class="howto_bar">
    </div>
    <div class="howto_text_title">
        고려대학교 제51대 총학생회장단 
        <br> 선거 투표장소
    </div>

<table>

<!-- 구글맵 Marker의 항목 이름들을 가림 - 관리자 모드에서 이걸 건드리기 때문
  <thead>
    <tr>
      <th>Name</th>
      <th>Placename</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  -->

  <tbody>
  <br>
    <div style='width: 330px;'>  
      <div id="map" style='width: 330px; height: 165px;'></div>  
    </div>

      <%# 원래 구글맵이 제공하는 구글맵 사이즈는 아래임.  %>
    <%# <div style='width: 800px;'>  
      <div id="map" style='width: 800px; height: 400px;'></div>  
    </div>   %>


    <script type="text/javascript">  
      handler = Gmaps.build('Google');  
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){  
      markers = handler.addMarkers(<%=raw @routers_default.to_json %>);  
      handler.bounds.extendWith(markers);  
      handler.fitMapToBounds();  
      });  
    </script>

<!-- 구글맵 위에 Marker를 만드는 Scaffold를 가림 - 관리자 모드에서 이걸 만들기 때문
    <% @routers.each do |router| %>
      <tr>
        <td><%= router.name %></td>
        <td><%= router.placename %></td>
        <td><%= router.latitude %></td>
        <td><%= router.longitude %></td>
        <td><%= link_to 'Show', router %></td>
        <td><%= link_to 'Edit', edit_router_path(router) %></td>
        <td><%= link_to 'Destroy', router, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    -->
  </tbody>
</table>

<br>

<%# <%= link_to 'New Router', new_router_path %>

app/views/routers/new.html.erb
<h1>투표장소 추가</h1>

<%= render 'form', router: @router %>

<%= link_to 'Back', routers_path %>

app/views/routers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @router.name %>
</p>

<p>
  <strong>Placename:</strong>
  <%= @router.placename %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @router.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @router.longitude %>
</p>

<%= link_to 'Edit', edit_router_path(@router) %> |
<%= link_to 'Back', routers_path %>