config/routes.rb
Rails.application.routes.draw do
  
  get '/hoowon2' => 'hoowon2#index'

  resources :hoowons
  get '/hoowons' => 'hoowon#index'
  get 'home/index'
  root 'vote_logs#index'

  #vote_logs routing
  resources :vote_logs
  resources :pledgenewees
  get 'home/index'
  post 'vote_logs/checkDouble' => 'vote_logs#checkDouble'

  #pledges routing
  get '/pledges' => 'pledges#index'
  

  #수영 routing
  get '/participate' => 'participate#index'
  get '/random' => 'lottos#new' 

  get 'home/quiz'     # 임시페이지
  get 'home/quizcard' # 임시페이지(블라인드공략테스트)
  resources :routers
  resources :voters
  resources :lottos
  devise_for :admins
  devise_for :users
  resources :pledgeintros

  get '/faq' => 'home#faq'
  get '/routers' => 'routers#index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin' # merge할 때 제일 마지막줄에 위치하게 해주세요!!
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
    mount_uploader :image, S3Uploader

end

app/controllers/vote_logs_controller.rb
require 'json'
class VoteLogsController < ApplicationController
  before_action :set_vote_log, only: [:show, :edit, :update, :destroy]


  # GET /vote_logs
  # GET /vote_logs.json
  def index
   
    @vote_logs = if params[:studentID]
      #검색 기능.
      VoteLog.where(" #{:studentID} LIKE ? ", params[:studentID])
    else
      VoteLog.order("created_at DESC").page params[:page]
    end 
    @vote_num = VoteLog.all
    @num = @vote_num.length
    
    # @vote_logs = VoteLog.order("created_at DESC").page params[:page]
    # @vote_my = VoteLog.where(" #{:studentID} == ? ", params[:studentID])
    # puts "============="
    # puts @vote_my.name
    # puts "============="
  end

  # GET /vote_logs/1
  # GET /vote_logs/1.json
  def show
  end

  # GET /vote_logs/new
  def new
    @vote_log = VoteLog.new
  end

  # GET /vote_logs/1/edit
  def edit
  end

  # POST /vote_logs
  # POST /vote_logs.json
  def create
    @vote_log = VoteLog.new(vote_log_params)

    respond_to do |format|
      if @vote_log.save
        format.html { redirect_to @vote_log, notice: 'Vote log was successfully created.' }
        format.json { render :show, status: :created, location: @vote_log }
      else
        format.html { render :new }
        format.json { render json: @vote_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vote_logs/1
  # PATCH/PUT /vote_logs/1.json
  def update
    respond_to do |format|
      if @vote_log.update(vote_log_params)
        format.html { redirect_to @vote_log, notice: 'Vote log was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote_log }
      else
        format.html { render :edit }
        format.json { render json: @vote_log.errors, status: :unprocessable_entity }
      end
    end
  end

  ##고려대학교 학생인지 확인 && 이미 참여한 기록은 없는지 확인
  def checkDouble
    puts "double checking"
    @studentID = params[:studentID]
    @name = params[:name]
    puts @studentID
    puts @name

    $result = {"IsStudent" => 0, "IsFirst" => 0, "canWrite" => 0}

    #고려대학교 학생인지 확인   Thing.exists?(params[:id])
    #@resultInDB = SchoolDb.where(studentID: @studentID)
    #puts @resultInDB.pluck(:studentID)##################################################

      #학교 db 내에 입력한 학번이 존재
      if SchoolDb.exists?(:name => @name)  #학교 db 내에 입력한 학번과 이름이 일치
        $result[:IsStudent] = 1
                
        #중복확인(교내 db와 일치하는 경우에만 실행하기 위함)
        if !VoteLog.exists?(:studentID => @studentID) #응모 기록 db에 입력한 학번이 존재하는지
          $result[:IsFirst] = 1
          $result[:canWrite] = 1    
        end
      end
  
      $result = $result.to_json
      puts $result

    respond_to do |format|
      format.json {render json: $result}
    end

    #$result = $result.to_json
    #puts "json 실행" + $result
   
  end

  # DELETE /vote_logs/1
  # DELETE /vote_logs/1.json
  def destroy
    @vote_log.destroy
    respond_to do |format|
      format.html { redirect_to vote_logs_url, notice: 'Vote log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote_log
      @vote_log = VoteLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_log_params
      params.require(:vote_log).permit(:studentID, :name, :image, :password, :phoneNum)
    end
end

app/helpers/vote_logs_helper.rb
module VoteLogsHelper
end

app/views/vote_logs/_form.html.erb
<!--<%= form_for(vote_log) do |f| %>
  <% if vote_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote_log.errors.count, "error") %> prohibited this vote_log from being saved:</h2>

      <ul>
      <% vote_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  -->



  <div class="field">
      <%= f.text_field :studentID, class: "vote-new-input mt-4", id: "studentID", placeholder: "학번을 입력해주세요"%>
  </div>

  <div class="field">
    <span class = "vote-new-outerbox">
      <%= f.text_field :name, class: "vote-new-input mt-4", id: "name", placeholder: "이름을 입력해주세요" %>    
    </span>
  </div>

  <p class = "mt-4 mb-2" id = "check-warning">본인 인증과 중복 확인을 위해 인증 버튼을 눌러주세요!</p>
  <button type = "button" id = "checkButton" class = "btn vote-new-btn-first">인증하기</button>

  <div class="field">
    <span class = "vote-new-outerbox">
      <%= f.text_field :phoneNum, class: "vote-new-input mt-4", id: "phoneNum", placeholder: "핸드폰 번호를 입력해주세요"%>
    </span>
  </div>

  <div class="field">
    <span class = "vote-new-outerbox">
      <%= f.password_field :password, class: "vote-new-input mt-4", id: "password", placeholder: "비밀번호를 입력해주세요"%>
    </span>
  </div>

  <div class="field">
    <%= f.file_field :image,
      accept: 'image/png, image/gif, image/jpeg', class: "vote-new-upload mt-4"%>
  </div>


<!--
  <div class="input-group">
  <div class="custom-file">
    <input accept = "image/png, image/gif, image/jpeg", type="file", class="custom-file-input", id="vote_log_image", name = "vote_log[image]">
    <label class="custom-file-label" for="vote_log_image">Choose file</label>
  </div>
  
  <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="button">Button</button>
  </div>
  -->
</div>


  <!--중복 확인된 경우에만 활성화!  안 된 경우에는 중복확인을 해 주세요 나타나있게 하기-->
  
  <div class="actions mt-4 d-flex flex-column justify-content-center align-items-center" id = "buttonDiv">
    <p id = "check-label" class = "text-center mb-0" style = "font-size: 0.8em;">아직 인증하지 않았습니다</p>
    <%= f.submit "응모하기", id: "submitButton", class: "btn vote-new-btn-second mt-1"%>
  </div>
<% end %>
 



<script>

  document.getElementById("submitButton").disabled = true;
  
  document.getElementById("checkButton").addEventListener("click", function(){
      
    //get element by ID
    var studentIdIn = document.getElementById("studentID").value;
    var nameIn = document.getElementById("name").value;
    $.ajax({
      async : true,
      type : "POST",
      data : {studentID : studentIdIn, name : nameIn},
      url : "checkDouble",
      dataType : "json",
      success : function(data){
        
        console.log(data);
      
      
        if (data["IsStudent"] == 0){
            document.getElementById("check-warning").innerHTML = "본교 학생이 아닙니다ㅠㅠ";
        }
        else if (data["IsFirst"] == 0){
            document.getElementById("check-warning").innerHTML = "이미 참여하셨습니다ㅠㅠㅠ";
        }
        else if (data["IsStudent"] ==1 && data["IsFirst"] == 1){
          document.getElementById("check-warning").innerHTML = "인증이 성공했습니다!";
          document.getElementById("submitButton").disabled = false;
          document.getElementById("check-label").innerHTML = "인증 완료, 응모 가능합니다 :)";
        }
        
    }
    })
    
  })
</script>

app/views/vote_logs/edit.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<%= link_to 'Destroy', @vote_log, class: "pass searchbtn", method: :delete, data: {confirm: "Are you sure?"} %>

<%= link_to 'Back', vote_logs_path, class: "searchbtn"%>
</div>

<script>
  var pass = document.querySelector(".pass");
    do{
      var a = prompt("인증코드를 입력하세요");
      if(a == '<%=@vote_log.password%>'){
      }
      else{
        alert("다시 입력해주세요");
      }
    }while(a!='<%=@vote_log.password%>');

</script>

app/views/vote_logs/index.html.erb
<%# 현재 투표율 %>
<div class="votenum_box d-flex justify-content-center">
  <div class="votenum_text">
    투표와 함께하는 즐거움<br>
    실시간 로또 참여인수
    <%# 투표 인원수 %>
    <div class="d-flex justify-content-center">
      <p id="counter1"></p>
    </div>
    <%= button_to "응모하기", new_vote_log_path, :class => "btn btn-outline-secondary btn_vote", :method => :get %>
  </div>
  
</div>
<div class="container">
<%# --------------참여방법 소개---------------- %>

<%# -------참여방법소개 끝----------- %>
  <p id="notice"><%= notice %></p>

  <%#= link_to '응모하기', new_vote_log_path %>
    <div class="row row_index">
    <% countvar = 0%>
      <% @vote_logs.each do |vote_log| %>
        <% break if countvar == 99 %>
        <%if countvar%3 == 2%>
          <figure class="snip1273 third_img">
            <%= image_tag vote_log.image , class: "vote_img"%>
            <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, edit_vote_log_path(vote_log)  %>
          </figure>

        <% else %>

          <figure class="snip1273">
            <%= image_tag vote_log.image , class: "vote_img"%>
            <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, edit_vote_log_path(vote_log)  %>
          </figure>

        <% end %>
        <% countvar = countvar + 1%>
    <% end %>
    </div>
  


  <%#= paginate @vote_logs %>
  <div class="searching">
    <%= form_tag(vote_logs_path, method: :get) do %>
      <%= text_field_tag :studentID, params[:studentID], placeholder: "학번을 입력하세요" %>
      <%= submit_tag 'Search', name: nil, class: "searchbtn" %>
    <% end %>

  </div>
</div>

<script>

    $(".vote_img").click(function() {
      $(this).toggleClass("experiment");
      $("i").toggleClass("after");
    });

  function numberCounter(target_frame, target_number) {
    this.count = 0; this.diff = 0;
    this.target_count = parseInt(target_number);
    this.target_frame = document.getElementById(target_frame);
    this.timer = null;
    this.counter();
  };
  numberCounter.prototype.counter = function() {
      var self = this;
      this.diff = this.target_count - this.count;
  
      if(this.diff > 0) {
          self.count += Math.ceil(this.diff / 5);
      }
  
      this.target_frame.innerHTML = this.count.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  
      if(this.count < this.target_count) {
          this.timer = setTimeout(function() { self.counter(); }, 300);
      } else {
          clearTimeout(this.timer);
      }
  };
var votenum = '<%=@num%>';

new numberCounter("counter1", votenum);
//vote count 끝---------------------

</script>
<%#= link_to 'New Vote Log', new_vote_log_path %>

app/views/vote_logs/new.html.erb
<div class = "container-fluid">
    <div class = "col-sm-11 col-xl-11 mx-auto px-0 py-0">
        <!--<div><%=image_tag("howto.jpg", class: "vote-new-image")%></div>-->
        <div class = "d-flex flex-column align-items-center">
            <%= render 'form', vote_log: @vote_log %>
        </div>

        <%= link_to '뒤로가기',  vote_logs_path, class: "float-right back-link" %>
    </div>
</div>

app/views/vote_logs/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Studentid:</strong>
  <%= @vote_log.studentID %>
</p>

<p>
  <strong>Name:</strong>
  <%= @vote_log.name %>
</p>

<%= link_to 'Destroy', edit_vote_log_path(@vote_log), class: "searchbtn" %>
<%= link_to 'Back', vote_logs_path, class: "searchbtn"%>
</div>